influxdb:
  image: influxdb:1.7.9
  ports:
    - 8086:8086

slack-counter:
  build: .
  links:
    - influxdb:influxdb
  ports:
    - "${SERVER_PORT}:${SERVER_PORT}"
  environment:
    - SLACK_TOKEN
    - SLACK_VERIFY_TOKEN
    - INFLUX_DB_URL=http://influxdb:8086
    - SERVER_PORT
    - INFLUX_DB_NAME=test
    - TEAM_ID
    - CHANNEL_ID
