influxdb:
  image: influxdb:1.7.9
  ports:
    - 8086:8086

slack-counter:
  build: .
  links:
    - influxdb:influxdb
  ports:
    - "8080:8080"
  environment:
    - SLACK_TOKEN
    - SLACK_VERIFY_TOKEN
