version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.5.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: ECR_URL
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          repo: slack-counter
          tag: "latest,${CIRCLE_SHA1}"
