version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/kirisaki/slack-count

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build exe binary
          command: go build

